---
- name: Update Proxmox server and all containers/VMs
  hosts: proxmox
  gather_facts: yes
  become: yes
  vars_files:
    - vault.yml

  tasks:
    - name: Update proxmox node
      ansible.builtin.apt:
        upgrade: dist
        cache_valid_time: 3600

    - name: Get list of all running containers
      ansible.builtin.shell: pct list | awk 'NR>1 {print $1}'
      register: container_list
      
    - name: Update all containers
      ansible.builtin.shell: pct exec {{ item }} -- bash -c "apt update && apt upgrade -y"
      loop: "{{ container_list.stdout_lines }}"

    - name: Get list of all running vms
      ansible.builtin.shell: qm list | awk 'NR>1 {print $1}'
      register: vm_list

    - name: Update all vms
      ansible.builtin.shell: qm guest exec {{ item }} -- bash -c "apt update && apt upgrade -y"
      loop: "{{ vm_list.stdout_lines }}"
    
